#!/bin/bash
callsign=$1
mode=$2
utc=$3
date=$4

if [  -e vviperlog.txt ]; then
	echo "Log file detected"
else
	echo "Creating log file"	
	touch vviperlog.txt
	echo "What is your callsign?"
	read ocs
	echo "log from ke2qso for $ocs" >> ke2qso.txt
fi


echo "$callsign    $mode    $utc $date" >> ke2qso.txt
echo "Contact logged :)"

